# Generated by Django 4.0.3 on 2022-03-14 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_treatment_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='cost',
        ),
    ]
