# Generated by Django 4.0.3 on 2022-03-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
